[package]
name = "mycrush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = { version = "0.4", features = ["std"] }
num-derive = "0.3"
num-traits = "0.2" # Explicitly add num-traits

[dev-dependencies]
crush-sys = { path = "../crush-sys" }
